use_frameworks!

target 'TestConnectionManager_Example' do
  pod 'TestConnectionManager', :path => '../'

  target 'TestConnectionManager_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
