use_frameworks!

target 'TestConnectionManager_Example' do
  pod 'TestConnectionManager', :path => '../'

  target 'TestConnectionManager_Tests' do
    pod 'TestConnectionManager', :path => '../'
  end
end
